wget -N https://www.dropbox.com/s/y7mdh4m9ptkibax/example_volumes.tar.gz
tar -xzvf example_volumes.tar.gz
wget -N https://www.dropbox.com/s/94wa4fl8f8k3aie/testing_data.tar.gz
tar -xzvf testing_data.tar.gz

python -m tests.mean_variance_normalisation_test
python -m tests.binary_masking_test
python -m tests.histogram_normalisation_test
python -m tests.volume_loader_test
python -m tests.activation_test
python -m tests.spatial_transformer_test
python -m tests.post_processing_test
python -m tests.bn_test
python -m tests.convolution_test
python -m tests.crop_test
python -m tests.deconvolution_test
python -m tests.deepmedic_test
python -m tests.dilatedcontext_test
python -m tests.downsample_test
python -m tests.elementwise_test
python -m tests.flip_test
python -m tests.grid_sampler_test
python -m tests.highres3dnet_test
python -m tests.highresblock_test
python -m tests.input_buffer_test
python -m tests.loss_test
python -m tests.rand_rotation_test
python -m tests.rand_spatial_scaling_test
python -m tests.scaleblock_test
python -m tests.scalenet_test
python -m tests.selective_sampler_test
python -m tests.subject_test
python -m tests.test_sample
python -m tests.toy_sampler_test
python -m tests.toynet_test
#python -m tests.unet_test
python -m tests.unetblock_test
python -m tests.uniform_sampler_test
python -m tests.upsample_test
python -m tests.vnet_test
python -m tests.vnetblock_test
