wget -N https://www.dropbox.com/s/y7mdh4m9ptkibax/example_volumes.tar.gz
tar -xzvf example_volumes.tar.gz
wget -N https://www.dropbox.com/s/94wa4fl8f8k3aie/testing_data.tar.gz
tar -xzvf testing_data.tar.gz

python -m niftynet.testing.mean_variance_normalisation_test
python -m niftynet.testing.binary_masking_test
python -m niftynet.testing.histogram_normalisation_test
python -m niftynet.testing.volume_loader_test
python -m niftynet.testing.activation_test
python -m niftynet.testing.spatial_transformer_test
python -m niftynet.testing.post_processing_test
python -m niftynet.testing.bn_test
python -m niftynet.testing.convolution_test
python -m niftynet.testing.crop_test
python -m niftynet.testing.deconvolution_test
python -m niftynet.testing.deepmedic_test
python -m niftynet.testing.dilatedcontext_test
python -m niftynet.testing.downsample_test
python -m niftynet.testing.elementwise_test
python -m niftynet.testing.flip_test
python -m niftynet.testing.grid_sampler_test
python -m niftynet.testing.highres3dnet_test
python -m niftynet.testing.highresblock_test
python -m niftynet.testing.input_buffer_test
python -m niftynet.testing.loss_test
python -m niftynet.testing.rand_rotation_test
python -m niftynet.testing.rand_spatial_scaling_test
python -m niftynet.testing.scaleblock_test
python -m niftynet.testing.scalenet_test
python -m niftynet.testing.selective_sampler_test
python -m niftynet.testing.subject_test
python -m niftynet.testing.test_sample
python -m niftynet.testing.toy_sampler_test
python -m niftynet.testing.toynet_test
#python -m niftynet.testing.unet_test
python -m niftynet.testing.unetblock_test
python -m niftynet.testing.uniform_sampler_test
python -m niftynet.testing.upsample_test
python -m niftynet.testing.vnet_test
python -m niftynet.testing.vnetblock_test
