wget -N https://www.dropbox.com/s/y7mdh4m9ptkibax/example_volumes.tar.gz
tar -xzvf example_volumes.tar.gz
wget -N https://www.dropbox.com/s/94wa4fl8f8k3aie/testing_data.tar.gz
tar -xzvf testing_data.tar.gz

python -m testing.mean_variance_normalisation_test
python -m testing.binary_masking_test
python -m testing.histogram_normalisation_test
python -m testing.volume_loader_test
python -m testing.activation_test
python -m testing.bn_test
python -m testing.convolution_test
python -m testing.crop_test
python -m testing.deconvolution_test
python -m testing.deepmedic_test
python -m testing.dilatedcontext_test
python -m testing.downsample_test
python -m testing.elementwise_test
python -m testing.grid_sampler_test
python -m testing.highres3dnet_test
python -m testing.highresblock_test
python -m testing.input_buffer_test
python -m testing.loss_test
python -m testing.rand_rotation_test
python -m testing.rand_spatial_scaling_test
python -m testing.scaleblock_test
python -m testing.scalenet_test
python -m testing.selective_sampler_test
python -m testing.subject_test
python -m testing.test_sample
python -m testing.toy_sampler_test
python -m testing.toynet_test
#python -m testing.unet_test
python -m testing.unetblock_test
python -m testing.uniform_sampler_test
python -m testing.upsample_test
python -m testing.vnet_test
python -m testing.vnetblock_test
